### ISSUE TITLE
Add encode/* (e.g. httpx)

### ISSUE THREAD

**Issue by mgorny** [ShadowJonathan/nostalebots.xyz#10]
Originally hit by it on https://github.com/encodehttpcore but it seems they use it for all projects, e.g.: https://github.com/encode/django-rest-framework/issues/8987.

On the positive note, they usually do reply to reports timely.

**Comment by ShadowJonathan** [comment]
Also moved into a discussion, bah

**Comment by ShadowJonathan** [comment]
They seem to have dropped it for httpx: https://github.com/encode/httpx/pull/2412

**Comment by ShadowJonathan** [comment]
The only other repo i could find is httpcore: https://github.com/encode/httpcore/blob/master/.github/stale.yml
