### ISSUE TITLE
Reorder Head tags

### ISSUE THREAD

**Issue by foxwyn** [ShadowJonathan/nostalebots.xyz#17]
Idea to move the meta tag for viewport to be above the link tag pulling in the stylesheet. I've never seen them in that order, and wonder if it causes some obscure edge cases?

**Comment by ShadowJonathan** [comment]
Afaik it shouldn't, but I'll reorder them :3

**Comment by ShadowJonathan** [comment]
I don't think it'll create much issue, but i've reordered them regardless ^^
