### ISSUE TITLE
Replace font stack with system defaults

### ISSUE THREAD

**Issue by foxwyn** [ShadowJonathan/nostalebots.xyz#19]
Idea to replace the font declaration from using Arial, to instead use the magic font stack thingy that chooses the system/os preferred sans-serif font. Windows users see Segoe, Ubuntu users see Liberation sans, etc.

**Comment by ShadowJonathan** [comment]
Wym with "magic font stack"? I'm not entirely sure, do you mean for me to set the font to `sans-serif`, so it chooses whatever system font for that?

**Comment by foxwyn** [comment]
```css
font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
```

This is what I use. It tries to find a font that matches the system font.
