### ISSUE TITLE
Add python-poetry/poetry to the list

### ISSUE THREAD

**Issue by ptrcnull** [ShadowJonathan/nostalebots.xyz#8]
https://github.com/python-poetry/poetry/issues/9091

> designed to prevent future frustration with comments that create unwanted notifications (due to being off-topic/describing an unrelated issue) or are hard to discover and valuable (in the case of a bug that is not fully fixed)

**Comment by ShadowJonathan** [comment]
This feels like a similar issue to #12, and this is a one-time occurrence where they're just locking past issues, imo not the same as stale bots.
